# Generated by Django 5.2.10 on 2026-01-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_active_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
