# Generated by Django 5.2.2 on 2026-01-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_wallet_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
