# Generated by Django 5.2.10 on 2026-01-27 01:43

import courses.models
import courses.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_homework_submission_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file',
            field=models.FileField(upload_to='homework_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), courses.models.validate_file_size, courses.validators.validate_zip_file]),
        ),
    ]
