# Generated by Django 5.2.2 on 2026-01-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduverse', '0002_homework_homeworksubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_at'], 'verbose_name': 'Current Task', 'verbose_name_plural': 'Current Tasks'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
