# Generated by Django 5.2.2 on 2026-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduverse', '0003_alter_homework_options_blogpost_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eduversevideo',
            name='is_premium',
            field=models.BooleanField(default=True, help_text='If true, only premium users can watch this'),
        ),
    ]
