# Generated by Django 5.2.2 on 2026-01-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduverse', '0004_eduversevideo_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='file_url',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='submissions/'),
        ),
    ]
