# Generated by Django 5.2.10 on 2026-01-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduverse', '0005_alter_homeworksubmission_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksubmission',
            name='content',
            field=models.TextField(blank=True, help_text="Student's answer or solution", null=True),
        ),
    ]
