# Generated by Django 5.2.10 on 2026-01-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='learning_groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='users.studygroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='users.studygroup'),
        ),
    ]
