# Generated by Django 5.2.10 on 2026-01-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studygroup_user_learning_groups_user_teaching_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=2),
        ),
    ]
