# Generated by Django 5.2.2 on 2026-01-27 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_days',
            field=models.IntegerField(default=0, help_text='Consecutive days of activity'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='User avatar image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, help_text='Virtual currency for shop purchases'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_premium',
            field=models.BooleanField(default=False, help_text='Premium subscription status'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_activity_date',
            field=models.DateField(auto_now=True, help_text='Last activity date for streak tracking'),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0, help_text='Points earned from competitions and activities'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, help_text='Premium expiration date', null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about attendance')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studygroup')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'group', 'date')},
            },
        ),
    ]
