# Generated by Django 5.2.2 on 2026-01-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_activity_days_user_avatar_url_user_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='days_of_week',
            field=models.JSONField(default=list, help_text='List of days, e.g. ["Monday", "Wednesday"]'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
