# Generated by Django 5.2.2 on 2026-01-28 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studygroup_days_of_week_studygroup_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher for this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
