# Generated by Django 5.2.10 on 2026-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_last_wpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_wpm',
            field=models.FloatField(default=0, help_text='Maximum typing speed achieved (words per minute)'),
        ),
    ]
